# Generated by Django 5.1.3 on 2024-11-14 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BtnCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter_title', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='title')),
                ('visit_counter', models.IntegerField(default=0, verbose_name='visit count')),
            ],
            options={
                'verbose_name': 'visit counter',
                'verbose_name_plural': 'visits counter',
            },
        ),
    ]
